In [1]:
import pandas as pd
df = pd.read_csv('學生成績.csv')
display(df)

#視覺美化資料表
def less60(v,prop=''):
    return prop if v < 60 else None

df.style\
.map(less60,prop='color:red;',subset=["國文","英文","數學","地理","歷史"])\
.format(precision=2,subset=["平均"])

    學號   姓名   國文  英文   數學   地理  歷史   總分    平均    你好
0    1  張俊傑   95  63   73   82  76  389  77.8  77.8
1    2  黃麗美   82  98   92   63  50  385  77.0  77.0
2    3  程玫靖   66  93   83   94  96  432  86.4  86.4
3    4  簡美君   91  86   71   65  59  372  74.4  74.4
4    5  呂傑宣   55  73   77   98  81  384  76.8  76.8
5    6  黃嘉琪   90  58   70   83  95  396  79.2  79.2
6    7  周琬婷   80  98   82   55  57  372  74.4  74.4
7    8  童建霖   85  83   77   98  93  436  87.2  87.2
8    9  柯韋成   72  93   88   90  95  438  87.6  87.6
9   10  林冠蕙   70  84   75   68  62  359  71.8  71.8
10  11  楊韋廷   63  52   86   75  53  329  65.8  65.8
11  12  吳柏誠   77  50   58   61  71  317  63.4  63.4
12  13  孫宜珊   66  55   85   87  88  381  76.2  76.2
13  14  林怡偉  100  82   73   63  98  416  83.2  83.2
14  15  謝水儒   96  50   78   69  55  348  69.6  69.6
15  16  張彥博   89  77   96   59  96  417  83.4  83.4
16  17  楊韻如   64  82   92   56  56  350  70.0  70.0
17  18  鄭憲定   75  64   89   95  58  381  76.2  76.2
18  19  簡國瑋   60  51   70   51  81  313  62.6  62.6
19  20  楊韋廷   97  85   66   89  98  435  87.0  87.0
20  21  黃淑芬   66  85   55   57  56  319  63.8  63.8
21  22  邱亭君   88  97   78   71  61  395  79.0  79.0
22  23  戴萱能   89  83   50   79  83  384  76.8  76.8
23  24  陳筱涵   85  99   88   83  77  432  86.4  86.4
24  25  王德城   51  61   52   75  96  335  67.0  67.0
25  26  高信宏   73  96   86   88  93  436  87.2  87.2
26  27  方雅慧   74  67   97   75  83  396  79.2  79.2
27  28  金宜芳   62  77   98   82  56  375  75.0  75.0
28  29  陳信念   92  84   83   78  99  436  87.2  87.2
29  30  朱惠儀   64  65   73   60  74  336  67.2  67.2
30  31  王明昇   89  55   78   64  84  370  74.0  74.0
31  32  孫火清   91  53   81   96  90  411  82.2  82.2
32  33  劉雯芬   71  81   69   92  99  412  82.4  82.4
33  34  張明惟   55  94   86   95  79  409  81.8  81.8
34  35  錢欣潔   85  67   95   69  80  396  79.2  79.2
35  36  柯宜臻   86  99   72   84  71  412  82.4  82.4
36  37  程玫靖   55  55   67   91  60  328  65.6  65.6
37  38  劉依婷   86  63   67   95  90  401  80.2  80.2
38  39  陳建香   92  62   70   60  77  361  72.2  72.2
39  40  楊又源   92  98   88  100  70  448  89.6  89.6
40  41  游詩亞   61  89   71   59  83  363  72.6  72.6
41  42  崔孝憲   72  59   62   60  82  335  67.0  67.0
42  43  陳逸華   99  80   94   65  87  425  85.0  85.0
43  44  孫火清   80  55   57   63  85  340  68.0  68.0
44  45  張凱妮   66  88   71   98  75  398  79.6  79.6
45  46  鄭佳玲   84  56   78   50  81  349  69.8  69.8
46  47  黃志福   82  57   67   58  66  330  66.0  66.0
47  48  高士凱   86  79  100   61  81  407  81.4  81.4
48  49  藍哲嘉   75  78   92   53  69  367  73.4  73.4
49  50  李政白   76  56   91   85  55  363  72.6  72.6